# Selfhosted
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:13306/Clear
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  data:
    redis:
      host: ${REDIS_HOST}
      port: 26739
      password: ${REDIS_PASSWORD}
      database: 0