server:
  port: 8888
  servlet:
    context-path: /api

spring:
  profiles:
    active: prod


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.wind.clear.entity
  configuration:
    map-underscore-to-camel-case: true


clear:
  jwt:
    # 设置签名加密时使用的密钥
    secret-key: ${SECRET_KEY}
    # 设置jwt过期时间
    ttl: 720000000
    # 设置前端传递过来的令牌名称
    token-name: ${TOKEN_NAME}
