server:
  port: 6633
  host: "0.0.0.0"
  mode: "release" # 可选值: debug, release

database:
    type: "sqlite"
    path: "data/clear.db"

auth:
  jwt:
    expires: 2592000 # 30天（单位秒）
    issuer: "clears"
    audience: "clears"

