name: Release Clear Desktop

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pnpm install
        working-directory: web

      - name: Build tauri app
        run: pnpm run tauri build
        working-directory: web

      - name: Upload executables to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            web/src-tauri/target/release/bundle/nsis/clear-desktop.exe
            web/src-tauri/target/release/bundle/nsis/clear-desktop_0.1.0_x64-setup.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}